# Folosește imaginea oficială Python 3.10 slim ca bază
FROM python:3.10-slim

# Setează directorul de lucru
#WORKDIR /usr/local/bin

# Actualizează pip și instalează dependențele necesare
RUN pip install --upgrade pip && \
    pip install psutil

# Copiază scriptul Python în container
COPY python_script.py /usr/local/bin/python_script.py

#Facem scriptul executabil
RUN chmod +x /usr/local/bin/python_script.py

# Comanda implicită care rulează scriptul Python
CMD ["python3" , "/usr/local/bin/python_script.py"]
