#Imagine OS
FROM ubuntu:latest

#update si instalare pachete necesare
RUN apt-get update && \
    apt-get install -y \
    bash \
    procps \
    coreutils 

#Copiere script in container
COPY bash_script.sh /usr/local/bin/bash_script.sh

#Facem script-ul executabil
RUN chmod +x /usr/local/bin/bash_script.sh

#Executam script-ul
CMD ["/usr/local/bin/bash_script.sh"]
